import { CommandGroups } from "..";

// source of truth, taken from https://github.com/rxhanson/RectanglePro-Community?tab=readme-ov-file#programmatically-triggering-window-sizes--positions
export const actions = [
  "left-half",
  "right-half",
  "maximize",
  "maximize-height",
  "previous-display",
  "next-display",
  "larger",
  "smaller",
  "bottom-half",
  "top-half",
  "center",
  "bottom-left",
  "bottom-right",
  "top-left",
  "top-right",
  "restore",
  "first-third",
  "first-two-thirds",
  "center-third",
  "last-two-thirds",
  "last-third",
  "move-left",
  "move-right",
  "move-up",
  "move-down",
  "almost-maximize",
  "fill-left",
  "fill-right",
  "center-half",
  "first-fourth",
  "second-fourth",
  "third-fourth",
  "last-fourth",
  "top-left-sixth",
  "top-center-sixth",
  "top-right-sixth",
  "bottom-left-sixth",
  "bottom-center-sixth",
  "bottom-right-sixth",
  "first-sixth",
  "last-sixth",
  "fullscreen",
  "close",
  "minimize",
  "quit-app",
  "hide-app",
  "cascade-all",
  "cascade-app",
  "tile-2x2",
  "tile-2x3",
  "reveal-desktop-edge",
  "app-next-display",
  "app-prev-display",
  "app-left-half",
  "app-right-half",
  "first-three-fourths",
  "last-three-fourths",
  "top-left-ninth",
  "top-center-ninth",
  "top-right-ninth",
  "middle-left-ninth",
  "middle-center-ninth",
  "middle-right-ninth",
  "bottom-left-ninth",
  "bottom-center-ninth",
  "bottom-right-ninth",
  "top-left-third",
  "top-right-third",
  "bottom-left-third",
  "bottom-right-third",
  "top-left-eighth",
  "top-center-left-eighth",
  "top-center-right-eighth",
  "top-right-eighth",
  "bottom-left-eighth",
  "bottom-center-left-eighth",
  "bottom-center-right-eighth",
  "bottom-right-eighth",
  "center-two-thirds",
  "fill-bottom-left",
  "fill-bottom-right",
  "fill-top-left",
  "fill-top-right",
  "last",
  "next-space",
  "nudge-left",
  "nudge-right",
  "nudge-up",
  "nudge-down",
  "prev-space",
  "snap-bottom-left",
  "snap-bottom-right",
  "snap-top-left",
  "snap-top-right",
  "upper-center",
  "next-display-ratio",
  "prev-display-ratio",
  "stash-left",
  "stash-right",
  "stash-up",
  "stash-down",
  "unstash",
  "cycle-stashed",
  "toggle-stashed",
  "unstash-all",
  "stash-all",
  "stash-all-but-front",
  "reflow-pin",
  "next-space",
  "prev-space",
] as const;

export type RectangleProAction = (typeof actions)[number];

export const commandGroups = {
  halves: {
    title: "Halves",
    items: [
      {
        name: "left-half",
        title: "Left Half",
        icon: "window-positions/leftHalfTemplate.png",
        description: "Move the focused window to the left half of the current display",
      },
      {
        name: "right-half",
        title: "Right Half",
        icon: "window-positions/rightHalfTemplate.png",
        description: "Move the focused window to the right half of the current display",
      },
      {
        name: "center-half",
        title: "Center Half",
        icon: "window-positions/halfWidthCenterTemplate.png",
        description: "Center the focused window in half-width",
      },
      {
        name: "top-half",
        title: "Top Half",
        icon: "window-positions/topHalfTemplate.png",
        description: "Move the focused window to the top half of the current display",
      },
      {
        name: "bottom-half",
        title: "Bottom Half",
        icon: "window-positions/bottomHalfTemplate.png",
        description: "Move the focused window to the bottom half of the current display",
      },
    ],
  },
  thirds: {
    title: "Thirds",
    items: [
      {
        name: "first-third",
        title: "First Third",
        icon: "window-positions/firstThirdTemplate.png",
        description: "Resize the focused window to the first third of the screen",
      },
      {
        name: "last-third",
        title: "Last Third",
        icon: "window-positions/lastThirdTemplate.png",
        description: "Resize the focused window to the last third of the screen",
      },
      {
        name: "first-two-thirds",
        title: "First Two Thirds",
        icon: "window-positions/firstTwoThirdsTemplate.png",
        description: "Resize the focused window to the first two-thirds of the screen",
      },
      {
        name: "center-third",
        title: "Center Third",
        icon: "window-positions/centerThirdTemplate.png",
        description: "Resize the focused window to the center third of the screen",
      },
      {
        name: "last-two-thirds",
        title: "Last Two Thirds",
        icon: "window-positions/lastTwoThirdsTemplate.png",
        description: "Resize the focused window to the last two-thirds of the screen",
      },
      {
        name: "first-three-fourths",
        title: "First Three Fourths",
        icon: "window-positions/firstThreeFourthsTemplate.png",
        description: "Resize the focused window to the first three-fourths of the screen",
      },
      {
        name: "last-three-fourths",
        title: "Last Three Fourths",
        icon: "window-positions/lastThreeFourthsTemplate.png",
        description: "Resize the focused window to the last three-fourths of the screen",
      },
    ],
  },
  fourths: {
    title: "Fourths",
    items: [
      {
        name: "first-fourth",
        title: "First Fourth",
        icon: "window-positions/leftFourthTemplate.png",
        description: "Resize the focused window to the first fourth of the screen",
      },
      {
        name: "second-fourth",
        title: "Second Fourth",
        icon: "window-positions/centerLeftFourthTemplate.png",
        description: "Resize the focused window to the second fourth of the screen",
      },
      {
        name: "third-fourth",
        title: "Third Fourth",
        icon: "window-positions/centerRightFourthTemplate.png",
        description: "Resize the focused window to the third fourth of the screen",
      },
      {
        name: "last-fourth",
        title: "Last Fourth",
        icon: "window-positions/rightFourthTemplate.png",
        description: "Resize the focused window to the last fourth of the screen",
      },
    ],
  },
  sixths: {
    title: "Sixths",
    items: [
      {
        name: "top-left-sixth",
        title: "Top Left Sixth",
        icon: "window-positions/topLeftSixthTemplate.png",
        description: "Resize the focused window to the top-left sixth of the screen",
      },
      {
        name: "top-center-sixth",
        title: "Top Center Sixth",
        icon: "window-positions/topCenterSixthTemplate.png",
        description: "Resize the focused window to the top-center sixth of the screen",
      },
      {
        name: "top-right-sixth",
        title: "Top Right Sixth",
        icon: "window-positions/topRightSixthTemplate.png",
        description: "Resize the focused window to the top-right sixth of the screen",
      },
      {
        name: "bottom-left-sixth",
        title: "Bottom Left Sixth",
        icon: "window-positions/bottomLeftSixthTemplate.png",
        description: "Resize the focused window to the bottom-left sixth of the screen",
      },
      {
        name: "bottom-center-sixth",
        title: "Bottom Center Sixth",
        icon: "window-positions/bottomCenterSixthTemplate.png",
        description: "Resize the focused window to the bottom-center sixth of the screen",
      },
      {
        name: "bottom-right-sixth",
        title: "Bottom Right Sixth",
        icon: "window-positions/bottomRightSixthTemplate.png",
        description: "Resize the focused window to the bottom-right sixth of the screen",
      },
      {
        name: "first-sixth",
        title: "First Sixth",
        icon: "window-positions/leftSixthTemplate.png",
        description: "Resize the focused window to the first sixth of the screen",
      },
      {
        name: "last-sixth",
        title: "Last Sixth",
        icon: "window-positions/rightSixthTemplate.png",
        description: "Resize the focused window to the last sixth of the screen",
      },
    ],
  },
  ninths: {
    title: "Ninths",
    items: [
      {
        name: "top-left-ninth",
        title: "Top Left Ninth",
        icon: "window-positions/tlNinthTemplate.png",
        description: "Resize the focused window to the top-left ninth of the screen",
      },
      {
        name: "top-center-ninth",
        title: "Top Center Ninth",
        icon: "window-positions/tNinthTemplate.png",
        description: "Resize the focused window to the top-center ninth of the screen",
      },
      {
        name: "top-right-ninth",
        title: "Top Right Ninth",
        icon: "window-positions/trNinthTemplate.png",
        description: "Resize the focused window to the top-right ninth of the screen",
      },
      {
        name: "middle-left-ninth",
        title: "Middle Left Ninth",
        icon: "window-positions/lNinthTemplate.png",
        description: "Resize the focused window to the middle-left ninth of the screen",
      },
      {
        name: "middle-center-ninth",
        title: "Middle Center Ninth",
        icon: "window-positions/cNinthTemplate.png",
        description: "Resize the focused window to the middle-center ninth of the screen",
      },
      {
        name: "middle-right-ninth",
        title: "Middle Right Ninth",
        icon: "window-positions/rNinthTemplate.png",
        description: "Resize the focused window to the middle-right ninth of the screen",
      },
      {
        name: "bottom-left-ninth",
        title: "Bottom Left Ninth",
        icon: "window-positions/blNinthTemplate.png",
        description: "Resize the focused window to the bottom-left ninth of the screen",
      },
      {
        name: "bottom-center-ninth",
        title: "Bottom Center Ninth",
        icon: "window-positions/bNinthTemplate.png",
        description: "Resize the focused window to the bottom-center ninth of the screen",
      },
      {
        name: "bottom-right-ninth",
        title: "Bottom Right Ninth",
        icon: "window-positions/brNinthTemplate.png",
        description: "Resize the focused window to the bottom-right ninth of the screen",
      },
    ],
  },
  eighths: {
    title: "Eighths",
    items: [
      {
        name: "top-left-eighth",
        title: "Top Left Eighth",

        icon: "window-positions/tlEighthTemplate.png",
        description: "Resize the focused window to the top-left eighth of the screen",
      },
      {
        name: "top-center-left-eighth",
        title: "Top Center Left Eighth",
        icon: "window-positions/ctlEighthTemplate.png",
        description: "Resize the focused window to the top-center-left eighth of the screen",
      },
      {
        name: "top-center-right-eighth",
        title: "Top Center Right Eighth",
        icon: "window-positions/ctrEighthTemplate.png",
        description: "Resize the focused window to the top-center-right eighth of the screen",
      },
      {
        name: "top-right-eighth",
        title: "Top Right Eighth",
        icon: "window-positions/trEighthTemplate.png",
        description: "Resize the focused window to the top-right eighth of the screen",
      },
      {
        name: "bottom-left-eighth",
        title: "Bottom Left Eighth",
        icon: "window-positions/blEighthTemplate.png",
        description: "Resize the focused window to the bottom-left eighth of the screen",
      },
      {
        name: "bottom-center-left-eighth",
        title: "Bottom Center Left Eighth",
        icon: "window-positions/cblEighthTemplate.png",
        description: "Resize the focused window to the bottom-center-left eighth of the screen",
      },
      {
        name: "bottom-center-right-eighth",
        title: "Bottom Center Right Eighth",
        icon: "window-positions/cbrEighthTemplate.png",
        description: "Resize the focused window to the bottom-center-right eighth of the screen",
      },
      {
        name: "bottom-right-eighth",
        title: "Bottom Right Eighth",
        icon: "window-positions/brEighthTemplate.png",
        description: "Resize the focused window to the bottom-right eighth of the screen",
      },
    ],
  },
  snap: {
    title: "Snap",
    items: [
      {
        name: "snap-bottom-left",
        title: "Snap Bottom Left",
        icon: "window-positions/snapBottomLeftTemplate.png",
        description: "Snap the focused window to the bottom-left corner",
      },
      {
        name: "snap-bottom-right",
        title: "Snap Bottom Right",
        icon: "window-positions/snapBottomRightTemplate.png",
        description: "Snap the focused window to the bottom-right corner",
      },
      {
        name: "snap-top-left",
        title: "Snap Top Left",
        icon: "window-positions/snapTopLeftTemplate.png",
        description: "Snap the focused window to the top-left corner",
      },
      {
        name: "snap-top-right",
        title: "Snap Top Right",
        icon: "window-positions/snapTopRightTemplate.png",
        description: "Snap the focused window to the top-right corner",
      },
    ],
  },
  other: {
    title: "Other",
    items: [
      {
        name: "maximize",
        title: "Maximize",
        icon: "window-positions/maximizeTemplate.png",
        description: "Maximize the focused window",
      },
      {
        name: "almost-maximize",
        title: "Almost Maximize",
        icon: "window-positions/almostMaximizeTemplate.png",
        description: "Almost maximize the focused window",
      },
      {
        name: "bottom-left",
        title: "Bottom Left",
        icon: "window-positions/bottomLeftTemplate.png",
        description: "Move the focused window to the bottom left of the current display",
      },
      {
        name: "bottom-right",
        title: "Bottom Right",
        icon: "window-positions/bottomRightTemplate.png",
        description: "Move the focused window to the bottom right of the current display",
      },
      {
        name: "center",
        title: "Center",
        icon: "window-positions/centerTemplate.png",
        description: "Center the focused window on the current display",
      },
      {
        name: "larger",
        title: "Make Larger",
        icon: "window-positions/makeLargerTemplate.png",
        description: "Increase the size of the focused window",
      },
      {
        name: "smaller",
        title: "Make Smaller",
        icon: "window-positions/makeSmallerTemplate.png",
        description: "Decrease the size of the focused window",
      },
      {
        name: "maximize-height",
        title: "Maximize Height",
        icon: "window-positions/maximizeHeightTemplate.png",
        description: "Maximize the height of the focused window",
      },
      {
        name: "move-down",
        title: "Move Down",
        icon: "window-positions/moveDownTemplate.png",
        description: "Move the focused window down",
      },
      {
        name: "move-left",
        title: "Move Left",
        icon: "window-positions/moveLeftTemplate.png",
        description: "Move the focused window to the left",
      },
      {
        name: "move-right",
        title: "Move Right",
        icon: "window-positions/moveRightTemplate.png",
        description: "Move the focused window to the right",
      },
      {
        name: "move-up",
        title: "Move Up",
        icon: "window-positions/moveUpTemplate.png",
        description: "Move the focused window up",
      },
      {
        name: "next-display",
        title: "Next Display",
        icon: "window-positions/nextDisplayTemplate.png",
        description: "Move the focused window to the next display",
      },
      {
        name: "previous-display",
        title: "Previous Display",
        icon: "window-positions/prevDisplayTemplate.png",
        description: "Move the focused window to the previous display",
      },
      {
        name: "restore",
        title: "Restore",
        icon: "window-positions/restoreTemplate.png",
        description: "Restore the focused window to its original size and position",
      },
      {
        name: "top-left",
        title: "Top Left",
        icon: "window-positions/topLeftTemplate.png",
        description: "Move the focused window to the top left of the current display",
      },
      {
        name: "top-right",
        title: "Top Right",
        icon: "window-positions/topRightTemplate.png",
        description: "Move the focused window to the top right of the current display",
      },
      {
        name: "last",
        title: "Last",
        icon: "window-positions/lastTemplate.png",
        description: "Select the last window",
      },
      {
        name: "next-space",
        title: "Next Space",
        icon: "window-positions/nextSpaceTemplate.png",
        description: "Move the focused window to the next space",
      },
      {
        name: "nudge-left",
        title: "Nudge Left",
        icon: "window-positions/nudgeLeftTemplate.png",
        description: "Nudge the focused window to the left",
      },
      {
        name: "nudge-right",
        title: "Nudge Right",
        icon: "window-positions/nudgeRightTemplate.png",
        description: "Nudge the focused window to the right",
      },
      {
        name: "nudge-up",
        title: "Nudge Up",
        icon: "window-positions/nudgeUpTemplate.png",
        description: "Nudge the focused window up",
      },
      {
        name: "nudge-down",
        title: "Nudge Down",
        icon: "window-positions/nudgeDownTemplate.png",
        description: "Nudge the focused window down",
      },
      {
        name: "prev-space",
        title: "Previous Space",
        icon: "window-positions/prevSpaceTemplate.png",
        description: "Move the focused window to the previous space",
      },
      {
        name: "upper-center",
        title: "Upper Center",
        icon: "window-positions/upperCenterTemplate.png",
        description: "Move the focused window to the upper-center",
      },
      {
        name: "next-display-ratio",
        title: "Next Display Ratio",
        icon: "window-positions/nextDisplayCenterTemplate.png",
        description: "Move the focused window to the next display, keeping ratio",
      },
      {
        name: "prev-display-ratio",
        title: "Prev Display Ratio",
        icon: "window-positions/prevDisplayCenterTemplate.png",
        description: "Move the focused window to the previous display, keeping ratio",
      },
    ],
  },
} as const satisfies CommandGroups;

// The following commands did not have an icon template, so they've been omitted for now:
// 'specified',
// 'reverse-all',
// 'top-left-ninth',
// 'top-center-ninth',
// 'top-right-ninth',
// 'middle-left-ninth',
// 'middle-center-ninth',
// 'middle-right-ninth',
// 'bottom-left-ninth',
// 'bottom-center-ninth',
// 'bottom-right-ninth',
// 'top-left-third',
// 'top-right-third',
// 'bottom-left-third',
// 'bottom-right-third',
// 'top-left-eighth',
// 'top-center-left-eighth',
// 'top-center-right-eighth',
// 'top-right-eighth',
// 'bottom-left-eighth',
// 'bottom-center-left-eighth',
// 'bottom-center-right-eighth',
// 'bottom-right-eighth',
// 'tile-all',
// 'cascade-all'

// Once all commands have been implemented, the compiler can ensure none are missing
// by uncommenting the following lines:

// const allGroupedCommands = [
//   ...commandGroups.halves.items.map(({ name }) => name),
//   ...commandGroups.thirds.items.map(({ name }) => name),
//   ...commandGroups.fourths.items.map(({ name }) => name),
//   ...commandGroups.sixths.items.map(({ name }) => name),
//   ...commandGroups.eighths.items.map(({ name }) => name),
//   ...commandGroups.ninths.items.map(({ name }) => name),
//   ...commandGroups.snap.items.map(({ name }) => name),
//   ...commandGroups.other.items.map(({ name }) => name),
// ] as const satisfies typeof actions;
